services:
  - type: web
    name: digital-twin-prediction
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT